# app/models.py
from sqlalchemy import Column, Integer, String, Date, DateTime
from sqlalchemy.sql import func
from app.database import Base

class UploadFile(Base):
    __tablename__ = "upload_files"
    
    id = Column(Integer, primary_key=True, index=True)
    file_name = Column(String, unique=True, index=True)
    upload_date = Column(DateTime(timezone=True), server_default=func.now())
    file_hash = Column(String, unique=True)

class Record(Base):
    __tablename__ = "records"
    
    id = Column(Integer, primary_key=True, index=True)
    RptDt = Column(Date)
    TckrSymb = Column(String, index=True)
    Asst = Column(String)
    AsstDesc = Column(String)
    SgmtNm = Column(String)
    MktNm = Column(String)
    SctyCtgyNm = Column(String)
    XprtnDt = Column(Date)
    XprtnCd = Column(String)
    TradgStartDt = Column(Date)
    TradgEndDt = Column(Date)
    eCd = Column(String)
    ConvsCritNm = Column(String)
    MtrtyDtTrgtPt = Column(Date)
    ReqrdConvsInd = Column(String)
    ISIN = Column(String)
    CFICd = Column(String)
    DlvryNtceStartDt = Column(Date)
    DlvryNtceEndDt = Column(Date)
    OptnTp = Column(String)
    CtrctMltplr = Column(String)
    AsstQtnQty = Column(String)
    AllcnRndLot = Column(String)
    TradgCcy = Column(String)
    DlvryTpNm = Column(String)
    WdrwlDays = Column(String)
    WrkgDays = Column(String)
    ClnrDays = Column(String)
    RlvrBasePricNm = Column(String)
    OpngFutrPosDay = Column(String)
    SdTpCd1 = Column(String)
    UndrlygTckrSymb1 = Column(String)
    SdTpCd2 = Column(String)
    UndrlygTckrSymb2 = Column(String)
    PureGoldWght = Column(String)
    ExrcPric = Column(String)
    OptnStyle = Column(String)
    ValTpNm = Column(String)
    PrmUpfrntInd = Column(String)
    OpngPosLmtDt = Column(Date)
    DstrbtnId = Column(String)
    PricFctr = Column(String)
    DaysToSttlm = Column(String)
    SrsTpNm = Column(String)
    PrtcnFlg = Column(String)
    AutomtcExrcInd = Column(String)
    SpcfctnCd = Column(String)
    CrpnNm = Column(String)
    CorpActnStartDt = Column(Date)
    CtdyTrtmntTpNm = Column(String)
    MktCptlstn = Column(String)
    CorpGovnLvlNm = Column(String)
